#!/bin/sh

rst_file_path="/github/workspace"

if [ ! -e "$rst_file_path" ]
then
    echo >&2 "Error: ${rst_file_path} does not exist"
    exit 1
fi

failures=0
for file in $(find "$rst_file_path" -name \*.rst)
do
    echo "$file"
    /opt/github-rest2html/rest2html "$file" > /dev/null
    failures=$(($returncode+$?))
done

test $failures -eq 0 || exit 1
